[package]
name = "vectorized-wikipedia-search"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.12.1", features = ["serde"] }
once_cell = "1.21.3"
indicatif = "0.18.3"
serde = { version = "1.0", feature = ["derive"] }
bincode = { version = "2.0", features = ["serde"] }
